version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    env_file: .env
    container_name: gm-api

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_DB: "gmschool"
      POSTGRES_PASSWORD: "123456"
    container_name: gm-db

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    volumes:
      - ../pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: anderson@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123
      POSTGRES_DB: gmschool
    container_name: pgadmin
