version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - /src:/src
    env_file: .env

  db:
    image: postgres:13
    ports:
      - 8080:8080
    volumes:
      - ../pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "root"
      POSTGRES_DB: "gmschool"
      POSTGRES_PASSWORD: "123456"
